name: Semantic segmentation notebooks test

on:
  schedule:
    - cron: "23 11 * * SUN" # run every Sunday at 11:23am
  workflow_dispatch:

jobs:
  test-cv:
    name: Test semantic segmentation notebooks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        notebooks:
          - Computer_vision_workloads/Semantic_segmentation/Scaling_model_training.ipynb
          - Computer_vision_workloads/Semantic_segmentation/Scaling_batch_inference.ipynb
          - Computer_vision_workloads/Semantic_segmentation/Batch_inference_with_Ray_Datasets.ipynb
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "tests/semantic_segmentation_course/requirements.txt"
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "tests/semantic_segmentation_course/requirements.txt"
      - name: Run notebooks
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 40
          max_attempts: 2
          retry_on: timeout
          command: |
            echo "run ${{ matrix.notebooks }}"
            ipython ${{ matrix.notebooks }}
