name: Introductory scripts test

on:
  schedule:
    - cron: "21 10 * * SUN" # run every Sunday at 10:21am
  workflow_dispatch:

jobs:
  test-cv:
    name: Test introductory scripts
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scripts:
          - Introductory_modules/quickstart_with_Ray_AIR.py
          - Introductory_modules/quickstart_with_Ray_Core.py
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "tests/semantic_segmentation_course/requirements.txt"
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "tests/semantic_segmentation_course/requirements.txt"
      - name: Run scripts
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 2
          retry_on: timeout
          command: |
            echo "run ${{ matrix.scripts }}"
            python ${{ matrix.scripts }}
